I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 109, in script
    anon "- how i found her -"
Exception: Sayer 'anon' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 109, in script
    anon "- how i found her -"
  File "/Users/spaghettilover69420/Downloads/renpy-8.2.0-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/Users/spaghettilover69420/Downloads/renpy-8.2.0-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/spaghettilover69420/Downloads/renpy-8.2.0-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'anon' is not defined.

macOS-14.2.1-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
HapticMediaMushroom 1.0
Thu Apr 25 20:41:49 2024
